root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/api ./cmd/api"
bin = "./tmp/api"
delay = 1000
exclude_dir = ["tmp", "vendor"]
exclude_file = []
exclude_regex = ["_test.go"]
include_dir = ["cmd", "internal", "pkg"]
include_ext = ["go"]
kill_delay = "500ms"
log = "air-build.log"
poll = false
rerun = false
send_interrupt = true
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = true

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = false
keep_scroll = true
